<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Device.Domain\Device.Domain.csproj" />
    <ProjectReference Include="..\Device.Common\Device.Common.csproj" />
    <ProjectReference Include="..\Device.GrpcCommon\Device.GrpcCommon.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Device.GrpcClient</PackageId>
    <Version>1.0.2</Version>
    <Authors>Joseph Melberg</Authors>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.84.0" />
    <PackageReference Include="Grpc.StatusProto" Version="2.84.0" />
  </ItemGroup>

</Project>
