<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Device.Grpc\Device.Grpc.csproj" />
    <ProjectReference Include="..\Infrastructure.MongoDB\Infrastructure.MongoDB.csproj" />
    <ProjectReference Include="..\Infrastructure.Rabbit\Infrastructure.Rabbit.csproj" />
    <ProjectReference Include="..\Infrastructure.Mqtt\Infrastructure.Mqtt.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="InterMW.Authorizer.GrpcClient" Version="10.0.21" />
    <PackageReference Include="MelbergFramework.Application" Version="8.0.10" />
    <PackageReference Include="MelbergFramework.Infrastructure.Rabbit" Version="8.0.15" />
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <UserSecretsId>f712d5ad-4fed-471d-9c89-f86eb5ea796e</UserSecretsId>
  </PropertyGroup>

</Project>
